name: stba
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.10.16
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - asttokens==3.0.0
      - attrs==25.3.0
      - git+https://github.com/fra31/auto-attack
      - backcall==0.2.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - eagerpy==0.30.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fonttools==4.58.0
      - foolbox==3.3.4
      - fsspec==2025.5.0
      - gdown==5.1.0
      - geotorch==0.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hf-xet==1.1.2
      - huggingface-hub==0.32.0
      - idna==3.10
      - imageio==2.37.0
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lpips==0.1.4
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.2.1
      - pipreqs==0.5.0
      - platformdirs==4.3.8
      - prompt-toolkit==3.0.51
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - referencing==0.36.2
      - requests==2.32.3
      - robustbench==1.1
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.9
      - tinycss2==1.4.0
      - torch==2.7.0
      - torchdiffeq==0.2.5
      - torchvision==0.22.0
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.3.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - yarg==0.1.9